services:
  db:
    image: postgres:18
    container_name: datalaw_db
    environment:
      POSTGRES_USER: datalaw
      POSTGRES_PASSWORD: datalaw
      POSTGRES_DB: datalaw_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U datalaw -d datalaw_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: datalaw_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Ajuste essas variáveis conforme a necessidade do seu DataJudSettings
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=datalaw
      - DB_PASSWORD=datalaw
      - DB_NAME=datalaw_db
      - POSTGRES_SERVER=db
      - DATABASE_URL=postgresql://datalaw:datalaw@db:5432/datalaw_db


volumes:
  postgres_data:
