-- =============================================================================
-- DataLaw warehouse v1 — PostgreSQL
-- Docker entrypoint ready: /docker-entrypoint-initdb.d/init-warehouse.sql
-- =============================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;

COMMENT ON SCHEMA bronze IS 'Bronze: raw DataJud extracts. Append-only.';
COMMENT ON SCHEMA silver IS 'Silver: conformed process/movement model.';
COMMENT ON SCHEMA gold   IS 'Gold: dimensional star for Sprint 1 indicators.';

-- -----------------------------------------------------------------------------
-- bronze
-- -----------------------------------------------------------------------------

CREATE TABLE bronze.datajud_extract (
    extract_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tribunal_alias  TEXT        NOT NULL,
    tribunal_sigla  TEXT        NOT NULL,
    source_file     TEXT        NOT NULL,
    extracted_at    TIMESTAMPTZ NOT NULL,
    took_ms         INTEGER,
    timed_out       BOOLEAN,
    shards          JSONB,
    hit_count       INTEGER     NOT NULL CHECK (hit_count >= 0),
    payload         JSONB       NOT NULL,
    CONSTRAINT uq_datajud_extract_source_file UNIQUE (source_file)
);

COMMENT ON TABLE  bronze.datajud_extract IS
    'One row per ingestion file. payload is the full Elasticsearch response.';
COMMENT ON COLUMN bronze.datajud_extract.tribunal_alias IS
    'Path segment used in the API, e.g. api_publica_tjsp.';
COMMENT ON COLUMN bronze.datajud_extract.tribunal_sigla IS
    'Directory/sigla used by save_raw_response, e.g. tjsp -> TJSP.';
COMMENT ON COLUMN bronze.datajud_extract.payload IS
    'Raw JSON: took, timed_out, _shards, hits.';

CREATE TABLE bronze.datajud_hit (
    hit_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    extract_id BIGINT NOT NULL
        REFERENCES bronze.datajud_extract (extract_id) ON DELETE CASCADE,
    es_index   TEXT    NOT NULL,
    es_id      TEXT    NOT NULL,
    es_score   NUMERIC,
    source     JSONB   NOT NULL,
    CONSTRAINT uq_datajud_hit_extract_es UNIQUE (extract_id, es_id)
);

COMMENT ON TABLE  bronze.datajud_hit IS
    'One row per hits.hits[] element. source is _source, still nested.';
COMMENT ON COLUMN bronze.datajud_hit.es_id IS
    'Elasticsearch _id. In this TJSP extract it equals _source.id.';
COMMENT ON COLUMN bronze.datajud_hit.source IS
    'Unparsed _source: capa + assuntos[] + movimentos[].';

CREATE INDEX ix_datajud_hit_extract_id ON bronze.datajud_hit (extract_id);
CREATE INDEX ix_datajud_hit_es_id      ON bronze.datajud_hit (es_id);

-- -----------------------------------------------------------------------------
-- silver — reference / TPU
-- -----------------------------------------------------------------------------

CREATE TABLE silver.tribunal (
    sigla TEXT PRIMARY KEY,
    nome  TEXT NOT NULL
);

CREATE TABLE silver.grau (
    codigo    TEXT PRIMARY KEY,
    descricao TEXT NOT NULL
);

CREATE TABLE silver.formato (
    codigo INTEGER PRIMARY KEY,
    nome   TEXT NOT NULL
);

CREATE TABLE silver.sistema (
    codigo INTEGER PRIMARY KEY,
    nome   TEXT NOT NULL
);

CREATE TABLE silver.classe_processual (
    codigo INTEGER PRIMARY KEY,
    nome   TEXT NOT NULL
);

COMMENT ON TABLE silver.classe_processual IS
    'TPU processual class. Business key = classe.codigo.';

CREATE TABLE silver.assunto (
    codigo INTEGER PRIMARY KEY,
    nome   TEXT NOT NULL
);

COMMENT ON TABLE silver.assunto IS
    'TPU subject. Business key = assuntos[].codigo. NLP topic is a later column.';

CREATE TABLE silver.orgao_julgador (
    codigo                INTEGER PRIMARY KEY,
    nome                  TEXT    NOT NULL,
    codigo_municipio_ibge INTEGER,
    tribunal_sigla        TEXT    NOT NULL
        REFERENCES silver.tribunal (sigla)
);

COMMENT ON TABLE silver.orgao_julgador IS
    'CNJ organ/serventia. IBGE is present on the capa and often absent on the movement.';
COMMENT ON COLUMN silver.orgao_julgador.codigo IS
    'orgaoJulgador.codigo (int) / movimentos.orgaoJulgador.codigo (string -> int).';

CREATE INDEX ix_orgao_julgador_tribunal ON silver.orgao_julgador (tribunal_sigla);
CREATE INDEX ix_orgao_julgador_ibge     ON silver.orgao_julgador (codigo_municipio_ibge);

CREATE TABLE silver.tipo_movimento (
    codigo INTEGER PRIMARY KEY,
    nome   TEXT
);

COMMENT ON TABLE  silver.tipo_movimento IS
    'TPU movement type. nome is nullable because the source omits it on some codes.';
COMMENT ON COLUMN silver.tipo_movimento.nome IS
    'Last-seen movimentos.nome for this codigo. Event-level name lives on silver.movimento.';

CREATE TABLE silver.tipo_complemento (
    codigo    INTEGER PRIMARY KEY,
    descricao TEXT    NOT NULL
);

COMMENT ON TABLE silver.tipo_complemento IS
    'Tabulated complement variable, e.g. codigo 3 / descricao tipo_de_conclusao.';

CREATE TABLE silver.valor_complemento (
    tipo_complemento_codigo INTEGER NOT NULL
        REFERENCES silver.tipo_complemento (codigo),
    valor                   INTEGER NOT NULL,
    nome                    TEXT    NOT NULL,
    PRIMARY KEY (tipo_complemento_codigo, valor)
);

COMMENT ON TABLE silver.valor_complemento IS
    'Conformed label for a complement value, e.g. valor 36 = para julgamento.';

-- -----------------------------------------------------------------------------
-- silver — process grain
-- -----------------------------------------------------------------------------

CREATE TABLE silver.processo (
    processo_sk                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_datajud                    TEXT        NOT NULL,
    numero_processo               TEXT        NOT NULL,
    tribunal_sigla                TEXT        NOT NULL
        REFERENCES silver.tribunal (sigla),
    grau                          TEXT        NOT NULL
        REFERENCES silver.grau (codigo),
    classe_codigo                 INTEGER     NOT NULL
        REFERENCES silver.classe_processual (codigo),
    sistema_codigo                INTEGER     NOT NULL
        REFERENCES silver.sistema (codigo),
    formato_codigo                INTEGER     NOT NULL
        REFERENCES silver.formato (codigo),
    orgao_julgador_codigo         INTEGER     NOT NULL
        REFERENCES silver.orgao_julgador (codigo),
    nivel_sigilo                  INTEGER     NOT NULL DEFAULT 0
        CHECK (nivel_sigilo >= 0),
    data_ajuizamento              TIMESTAMPTZ NOT NULL,
    data_hora_ultima_atualizacao  TIMESTAMPTZ,
    source_extract_id             BIGINT
        REFERENCES bronze.datajud_extract (extract_id) ON DELETE SET NULL,
    ingested_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_processo_id_datajud UNIQUE (id_datajud),
    CONSTRAINT uq_processo_natural    UNIQUE (tribunal_sigla, grau, numero_processo)
);

COMMENT ON TABLE  silver.processo IS
    'One DataJud document. Natural key (tribunal, grau, numero_processo).';
COMMENT ON COLUMN silver.processo.id_datajud IS
    '_source.id. Opaque business key — do not parse.';
COMMENT ON COLUMN silver.processo.numero_processo IS
    'CNJ number, unformatted. TEXT to preserve leading zeros.';
COMMENT ON COLUMN silver.processo.data_ajuizamento IS
    'Parsed from compact YYYYMMDDHHMMSS or ISO-8601.';
COMMENT ON COLUMN silver.processo.orgao_julgador_codigo IS
    'Cover organ (current). Movement organs may differ; see silver.movimento.';

CREATE INDEX ix_processo_tribunal_ajuizamento
    ON silver.processo (tribunal_sigla, data_ajuizamento);
CREATE INDEX ix_processo_classe
    ON silver.processo (classe_codigo);
CREATE INDEX ix_processo_orgao
    ON silver.processo (orgao_julgador_codigo);
CREATE INDEX ix_processo_numero
    ON silver.processo (numero_processo);
CREATE INDEX ix_processo_extract
    ON silver.processo (source_extract_id);

CREATE TABLE silver.processo_assunto (
    processo_sk    BIGINT  NOT NULL
        REFERENCES silver.processo (processo_sk) ON DELETE CASCADE,
    assunto_codigo INTEGER NOT NULL
        REFERENCES silver.assunto (codigo),
    PRIMARY KEY (processo_sk, assunto_codigo)
);

COMMENT ON TABLE silver.processo_assunto IS
    'M:N process x TPU assunto. Replace-on-reload with the parent process.';

CREATE INDEX ix_processo_assunto_assunto ON silver.processo_assunto (assunto_codigo);

-- -----------------------------------------------------------------------------
-- silver — movement grain (synthesized; source has no movement id)
-- -----------------------------------------------------------------------------

CREATE TABLE silver.movimento (
    movimento_sk          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processo_sk           BIGINT      NOT NULL
        REFERENCES silver.processo (processo_sk) ON DELETE CASCADE,
    tipo_movimento_codigo INTEGER     NOT NULL
        REFERENCES silver.tipo_movimento (codigo),
    data_hora             TIMESTAMPTZ NOT NULL,
    orgao_julgador_codigo INTEGER     NOT NULL
        REFERENCES silver.orgao_julgador (codigo),
    nome_origem           TEXT,
    ordem_origem          INTEGER     NOT NULL
        CHECK (ordem_origem >= 0),
    CONSTRAINT uq_movimento_carga UNIQUE (processo_sk, ordem_origem)
);

COMMENT ON TABLE  silver.movimento IS
    'Unnested movimentos[]. Surrogate PK: the API does not emit a movement id.';
COMMENT ON COLUMN silver.movimento.ordem_origem IS
    '0-based index in the JSON array. Load-time discriminator only — not time.';
COMMENT ON COLUMN silver.movimento.nome_origem IS
    'movimentos.nome as received; null when the field is omitted.';
COMMENT ON COLUMN silver.movimento.orgao_julgador_codigo IS
    'Organ of the event. Differed from the cover organ on 334/5792 rows in the extract.';

CREATE INDEX ix_movimento_processo
    ON silver.movimento (processo_sk);
CREATE INDEX ix_movimento_tipo_data
    ON silver.movimento (tipo_movimento_codigo, data_hora);
CREATE INDEX ix_movimento_orgao
    ON silver.movimento (orgao_julgador_codigo);
CREATE INDEX ix_movimento_data_hora
    ON silver.movimento (data_hora);

CREATE TABLE silver.movimento_complemento (
    movimento_sk            BIGINT  NOT NULL
        REFERENCES silver.movimento (movimento_sk) ON DELETE CASCADE,
    tipo_complemento_codigo INTEGER NOT NULL,
    valor                   INTEGER NOT NULL,
    nome_origem             TEXT    NOT NULL,
    PRIMARY KEY (movimento_sk, tipo_complemento_codigo, valor),
    CONSTRAINT fk_mov_comp_valor
        FOREIGN KEY (tipo_complemento_codigo, valor)
        REFERENCES silver.valor_complemento (tipo_complemento_codigo, valor)
);

COMMENT ON TABLE silver.movimento_complemento IS
    'Unnested movimentos[].complementosTabelados[]. Snapshot name on nome_origem.';

CREATE INDEX ix_movimento_complemento_tipo
    ON silver.movimento_complemento (tipo_complemento_codigo, valor);

-- -----------------------------------------------------------------------------
-- gold — dimensions
-- -----------------------------------------------------------------------------

CREATE TABLE gold.dim_tempo (
    date_key        INTEGER PRIMARY KEY,
    data            DATE        NOT NULL UNIQUE,
    ano             SMALLINT    NOT NULL,
    trimestre       SMALLINT    NOT NULL CHECK (trimestre BETWEEN 1 AND 4),
    mes             SMALLINT    NOT NULL CHECK (mes BETWEEN 1 AND 12),
    mes_nome        TEXT        NOT NULL,
    ano_mes         TEXT        NOT NULL,
    semana_iso      SMALLINT    NOT NULL,
    dia             SMALLINT    NOT NULL,
    dia_semana_iso  SMALLINT    NOT NULL CHECK (dia_semana_iso BETWEEN 1 AND 7),
    dia_semana_nome TEXT        NOT NULL,
    fim_de_semana   BOOLEAN     NOT NULL
);

COMMENT ON TABLE gold.dim_tempo IS
    'Calendar 2010-01-01..2030-12-31. date_key = YYYYMMDD. Missing dates use NULL FKs, not a dummy row.';

CREATE TABLE gold.dim_tribunal (
    sigla TEXT PRIMARY KEY,
    nome  TEXT NOT NULL
);

CREATE TABLE gold.dim_grau (
    codigo    TEXT PRIMARY KEY,
    descricao TEXT NOT NULL
);

CREATE TABLE gold.dim_formato (
    codigo INTEGER PRIMARY KEY,
    nome   TEXT NOT NULL
);

CREATE TABLE gold.dim_sistema (
    codigo INTEGER PRIMARY KEY,
    nome   TEXT NOT NULL
);

CREATE TABLE gold.dim_classe (
    codigo INTEGER PRIMARY KEY,
    nome   TEXT NOT NULL
);

CREATE TABLE gold.dim_assunto (
    codigo INTEGER PRIMARY KEY,
    nome   TEXT NOT NULL
);

CREATE TABLE gold.dim_tipo_movimento (
    codigo INTEGER PRIMARY KEY,
    nome   TEXT
);

CREATE TABLE gold.dim_orgao_julgador (
    codigo                INTEGER PRIMARY KEY,
    nome                  TEXT    NOT NULL,
    codigo_municipio_ibge INTEGER,
    tribunal_sigla        TEXT    NOT NULL
        REFERENCES gold.dim_tribunal (sigla)
);

CREATE INDEX ix_dim_orgao_tribunal ON gold.dim_orgao_julgador (tribunal_sigla);

-- -----------------------------------------------------------------------------
-- gold — facts
-- -----------------------------------------------------------------------------

CREATE TABLE gold.fact_processo (
    processo_sk                  BIGINT PRIMARY KEY,
    id_datajud                   TEXT        NOT NULL,
    numero_processo              TEXT        NOT NULL,
    tribunal_sigla               TEXT        NOT NULL
        REFERENCES gold.dim_tribunal (sigla),
    grau                         TEXT        NOT NULL
        REFERENCES gold.dim_grau (codigo),
    classe_codigo                INTEGER     NOT NULL
        REFERENCES gold.dim_classe (codigo),
    orgao_codigo                 INTEGER     NOT NULL
        REFERENCES gold.dim_orgao_julgador (codigo),
    formato_codigo               INTEGER     NOT NULL
        REFERENCES gold.dim_formato (codigo),
    sistema_codigo               INTEGER     NOT NULL
        REFERENCES gold.dim_sistema (codigo),
    data_ajuizamento_key         INTEGER     NOT NULL
        REFERENCES gold.dim_tempo (date_key),
    data_baixa_key               INTEGER
        REFERENCES gold.dim_tempo (date_key),
    data_ultimo_movimento_key    INTEGER
        REFERENCES gold.dim_tempo (date_key),
    data_ajuizamento             TIMESTAMPTZ NOT NULL,
    data_evento_terminal         TIMESTAMPTZ,
    qtd_movimentos               INTEGER     NOT NULL CHECK (qtd_movimentos >= 0),
    qtd_assuntos                 INTEGER     NOT NULL CHECK (qtd_assuntos >= 0),
    duracao_dias                 INTEGER     CHECK (duracao_dias IS NULL OR duracao_dias >= 0),
    tem_baixa_definitiva         BOOLEAN     NOT NULL DEFAULT FALSE,
    tem_arquivamento_definitivo  BOOLEAN     NOT NULL DEFAULT FALSE,
    fonte                        TEXT        NOT NULL DEFAULT 'DataJud/CNJ',
    confiabilidade_score         NUMERIC(5, 4)
        CHECK (
            confiabilidade_score IS NULL
            OR (confiabilidade_score >= 0 AND confiabilidade_score <= 1)
        ),
    confiabilidade_motivo        TEXT,
    aderente_flag                BOOLEAN,
    resultado_codigo             TEXT,
    loaded_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fact_processo_id UNIQUE (id_datajud)
);

COMMENT ON TABLE  gold.fact_processo IS
    'Grain: one process. Volume, duration, terminal-movement flags, source/reliability.';
COMMENT ON COLUMN gold.fact_processo.processo_sk IS
    'Copied from silver.processo.processo_sk. Not a FK so gold can be rebuilt independently.';
COMMENT ON COLUMN gold.fact_processo.data_evento_terminal IS
    'dataHora of the first movement 22 or 246. Duration = this - data_ajuizamento.';
COMMENT ON COLUMN gold.fact_processo.tem_baixa_definitiva IS
    'Exists TPU 22 (Baixa Definitiva).';
COMMENT ON COLUMN gold.fact_processo.tem_arquivamento_definitivo IS
    'Exists TPU 246 (Definitivo).';
COMMENT ON COLUMN gold.fact_processo.fonte IS
    'Sprint 1.5 source label. Always DataJud/CNJ for this pipeline.';
COMMENT ON COLUMN gold.fact_processo.confiabilidade_score IS
    'ETL-derived 0-1 from sigilo, presenca de assuntos/movimentos, and freshness.';
COMMENT ON COLUMN gold.fact_processo.aderente_flag IS
    'Reserved. Null until the adherence business rule is confirmed.';
COMMENT ON COLUMN gold.fact_processo.resultado_codigo IS
    'Reserved outcome code. Null until classification exists.';

CREATE INDEX ix_fact_processo_tribunal_ajuiz
    ON gold.fact_processo (tribunal_sigla, data_ajuizamento_key);
CREATE INDEX ix_fact_processo_classe
    ON gold.fact_processo (classe_codigo);
CREATE INDEX ix_fact_processo_orgao
    ON gold.fact_processo (orgao_codigo);
CREATE INDEX ix_fact_processo_baixa
    ON gold.fact_processo (data_baixa_key);
CREATE INDEX ix_fact_processo_numero
    ON gold.fact_processo (numero_processo);

CREATE TABLE gold.fact_movimento (
    movimento_sk          BIGINT PRIMARY KEY,
    processo_sk           BIGINT      NOT NULL
        REFERENCES gold.fact_processo (processo_sk) ON DELETE CASCADE,
    tipo_movimento_codigo INTEGER     NOT NULL
        REFERENCES gold.dim_tipo_movimento (codigo),
    orgao_codigo          INTEGER     NOT NULL
        REFERENCES gold.dim_orgao_julgador (codigo),
    data_key              INTEGER     NOT NULL
        REFERENCES gold.dim_tempo (date_key),
    data_hora             TIMESTAMPTZ NOT NULL,
    nome                  TEXT,
    ordem_origem          INTEGER     NOT NULL CHECK (ordem_origem >= 0),
    tem_complementos      BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_fact_movimento_carga UNIQUE (processo_sk, ordem_origem)
);

COMMENT ON TABLE gold.fact_movimento IS
    'Grain: one movement event. Use for processing-time paths and movement mix.';

CREATE INDEX ix_fact_movimento_processo
    ON gold.fact_movimento (processo_sk);
CREATE INDEX ix_fact_movimento_tipo_data
    ON gold.fact_movimento (tipo_movimento_codigo, data_key);
CREATE INDEX ix_fact_movimento_orgao
    ON gold.fact_movimento (orgao_codigo);

CREATE TABLE gold.bridge_processo_assunto (
    processo_sk    BIGINT  NOT NULL
        REFERENCES gold.fact_processo (processo_sk) ON DELETE CASCADE,
    assunto_codigo INTEGER NOT NULL
        REFERENCES gold.dim_assunto (codigo),
    PRIMARY KEY (processo_sk, assunto_codigo)
);

COMMENT ON TABLE gold.bridge_processo_assunto IS
    'M:N bridge. Topic filter uses TPU assunto until NLP classification exists.';

CREATE INDEX ix_bridge_processo_assunto_assunto
    ON gold.bridge_processo_assunto (assunto_codigo);

-- -----------------------------------------------------------------------------
-- SEEDS — initial base values
-- -----------------------------------------------------------------------------

INSERT INTO silver.tribunal (sigla, nome) VALUES
    ('TJSP', 'Tribunal de Justiça do Estado de São Paulo')
ON CONFLICT (sigla) DO NOTHING;

INSERT INTO silver.grau (codigo, descricao) VALUES
    ('G1', 'Primeiro grau'),
    ('JE', 'Juizado Especial')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO silver.formato (codigo, nome) VALUES
    (1, 'Eletrônico')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO silver.sistema (codigo, nome) VALUES
    (4, 'Projudi')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO silver.tipo_movimento (codigo, nome) VALUES
    (22,  'Baixa Definitiva'),
    (246, 'Definitivo')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO gold.dim_tribunal (sigla, nome)
SELECT sigla, nome FROM silver.tribunal
ON CONFLICT (sigla) DO NOTHING;

INSERT INTO gold.dim_grau (codigo, descricao)
SELECT codigo, descricao FROM silver.grau
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO gold.dim_formato (codigo, nome)
SELECT codigo, nome FROM silver.formato
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO gold.dim_sistema (codigo, nome)
SELECT codigo, nome FROM silver.sistema
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO gold.dim_tipo_movimento (codigo, nome)
SELECT codigo, nome FROM silver.tipo_movimento
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO gold.dim_tempo (
    date_key,
    data,
    ano,
    trimestre,
    mes,
    mes_nome,
    ano_mes,
    semana_iso,
    dia,
    dia_semana_iso,
    dia_semana_nome,
    fim_de_semana
)
SELECT
    (EXTRACT(YEAR  FROM d)::INTEGER * 10000
     + EXTRACT(MONTH FROM d)::INTEGER * 100
     + EXTRACT(DAY   FROM d)::INTEGER),
    d::DATE,
    EXTRACT(YEAR    FROM d)::SMALLINT,
    EXTRACT(QUARTER FROM d)::SMALLINT,
    EXTRACT(MONTH   FROM d)::SMALLINT,
    (ARRAY[
        'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
        'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'
    ])[EXTRACT(MONTH FROM d)::INTEGER],
    to_char(d, 'YYYY-MM'),
    EXTRACT(WEEK    FROM d)::SMALLINT,
    EXTRACT(DAY     FROM d)::SMALLINT,
    EXTRACT(ISODOW  FROM d)::SMALLINT,
    (ARRAY[
        'Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira',
        'Sexta-feira', 'Sábado', 'Domingo'
    ])[EXTRACT(ISODOW FROM d)::INTEGER],
    EXTRACT(ISODOW FROM d) IN (6, 7)
FROM generate_series(DATE '2010-01-01', DATE '2030-12-31', INTERVAL '1 day') AS g(d)
ON CONFLICT (date_key) DO NOTHING;

COMMIT;

END;